// The feature table (docs/PRODUCT.md, section 0): the state of every feature, generated — never written by hand. It
// joins what the manifest declares (the group, the title, the scenarios, the behaviour section), what the inventory
// derives from the source (built or not, the modules behind it), what the behaviour spec asks (its "Required:" items)
// and what the runner recorded at the last complete browser run on a clean tree (docs/feature-results.json, written by
// tools/runner/status.ts). `npm run inventory` writes docs/FEATURES.md; `npm run inventory:check` fails while it is out
// of step with any of them.
import fs from 'node:fs';
import path from 'node:path';
import { REPO_ROOT } from '../manifest/load.ts';
import type { Inventory } from './generate.ts';

export const FEATURES_MD = path.join('docs', 'FEATURES.md');
export const FEATURE_RESULTS = path.join('docs', 'feature-results.json');

// What the runner records after a complete run on a clean tree: the commit, its date, and each feature's scenario
// tests.
export interface FeatureResults {
  readonly commit: string;
  readonly date: string;
  readonly tests: { readonly passed: number; readonly total: number };
  readonly features: Readonly<Record<string, { readonly passed: number; readonly total: number }>>;
}

interface ManifestFeature {
  readonly id: string;
  readonly titleKey: string;
  readonly spec: string;
  readonly scenarios: readonly { readonly doors: readonly string[] }[];
}

function readResults(): FeatureResults | null {
  const file = path.join(REPO_ROOT, FEATURE_RESULTS);
  return fs.existsSync(file) ? (JSON.parse(fs.readFileSync(file, 'utf8')) as FeatureResults) : null;
}

// the "Required:" items of each section of the behaviour spec, by its anchor
function requiredBySection(): ReadonlyMap<string, number> {
  const spec = fs.readFileSync(path.join(REPO_ROOT, 'spec', 'BEHAVIOUR.md'), 'utf8');
  const out = new Map<string, number>();
  for (const section of spec.split(/^## /m).slice(1)) {
    const id = section.slice(0, section.indexOf('\n')).trim();
    out.set(id, (section.match(/Required/g) ?? []).length);
  }
  return out;
}

const englishTitle = (key: string): string => {
  const catalogue = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'src', 'i18n', 'locales', 'en.json'), 'utf8')) as Record<string, unknown>;
  const flat = catalogue[key];
  if (typeof flat === 'string') return flat;
  const nested = key.split('.').reduce<unknown>((at, part) => (at !== null && typeof at === 'object' ? (at as Record<string, unknown>)[part] : undefined), catalogue);
  return typeof nested === 'string' ? nested : key;
};

export function featuresMarkdown(inventory: Inventory): string {
  const results = readResults();
  const required = requiredBySection();
  const rowOf = new Map(inventory.features.map((row) => [row.id, row]));
  const groups = fs
    .readdirSync(path.join(REPO_ROOT, 'manifest', 'features'))
    .filter((file) => /^\d\d-.*\.json$/.test(file))
    .sort()
    .map((file) => ({ group: file.replace(/\.json$/, ''), features: (JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'manifest', 'features', file), 'utf8')) as { features: ManifestFeature[] }).features }));
  const lines: string[] = [];
  lines.push('# Features', '');
  lines.push('Generated by `npm run inventory` (tools/inventory/features.ts) from the manifest, the source, the behaviour spec and');
  lines.push('the last complete browser run on a clean tree (`docs/feature-results.json`, written by the runner): never edited by');
  lines.push('hand. `npm run inventory:check` fails while this file is out of step. The requirements these features answer, and the');
  lines.push('open problems, are in `docs/PRODUCT.md`.', '');
  const t = inventory.totals;
  lines.push(`${t.features} features (${t.built} built), ${t.commands} commands, ${t.doors} doors, ${t.scenarios} scenarios.`);
  if (results === null) lines.push('', 'No complete browser run on a clean tree has been recorded yet: the next one writes `docs/feature-results.json`.');
  else {
    const passing = Object.values(results.features).filter((one) => one.passed === one.total).length;
    lines.push('', `Last complete browser run: commit \`${results.commit}\` (${results.date}), ${results.tests.passed} of ${results.tests.total} tests passed; ${passing} features passed every scenario test.`);
  }
  lines.push('', '"Required" counts the `Required:` items of the feature\'s section of `spec/BEHAVIOUR.md`; "none" means the feature has no section.');
  for (const { group, features } of groups) {
    lines.push('', `## ${group}`, '');
    lines.push('| Feature | Title | Built | Scenarios | Doors | Behaviour section | Required | Last complete run |');
    lines.push('|---|---|---|---|---|---|---|---|');
    for (const feature of features) {
      const row = rowOf.get(feature.id);
      const anchor = feature.spec.split('#')[1] ?? null;
      const run = results?.features[feature.id];
      const runText = row?.built !== true ? 'not built' : results === null ? '—' : run === undefined ? 'not in that run' : run.passed === run.total ? `passes ${run.passed}/${run.total}` : `FAILS ${run.passed}/${run.total}`;
      const doors = new Set(feature.scenarios.flatMap((one) => one.doors)).size;
      lines.push(`| \`${feature.id}\` | ${englishTitle(feature.titleKey).replaceAll('|', '\\|')} | ${row?.built === true ? 'yes' : 'not yet'} | ${feature.scenarios.length} | ${doors} | ${anchor === null ? 'none' : `[${anchor}](../spec/BEHAVIOUR.md#${anchor})`} | ${anchor === null ? '—' : String(required.get(anchor) ?? 0)} | ${runText} |`);
    }
  }
  lines.push('');
  return lines.join('\n');
}
