// docs/PAIRING.md, written from docs/pairing.json (npm run parity) and the recorded decisions
// (tools/parity/decisions.json): how many regions and controls each pair compares and how many diverge, the open
// divergences grouped by what diverges, and those a decision keeps. tools/parity/pairing.test.ts holds the document to
// this writer, as inventory:check holds the inventory.
//   node tools/parity/report.ts
import fs from 'node:fs';
import path from 'node:path';

export interface Divergence {
  readonly kind: 'region' | 'control';
  readonly id: string;
  readonly property: string;
  readonly canon: string;
  readonly app: string;
}
export interface Pair {
  readonly state: string;
  readonly theme: string;
  readonly language: string;
  readonly regions: number;
  readonly controls: number;
  readonly divergences: readonly Divergence[];
}
export interface Decision {
  readonly decision: string;
  readonly why: string;
  // what it keeps: a divergence whose kind, mark (a control's door without its order) and property match each given
  readonly matches: readonly { readonly kind?: string; readonly id: string; readonly property?: string; readonly state?: string }[];
}

export interface Face {
  readonly mark: string;
  readonly side: 'app' | 'canon';
  readonly closest?: string;
  readonly inside?: string;
  readonly why: string;
}
export interface Alias {
  readonly door: string;
  readonly as: readonly string[];
  readonly why: string;
}

const mark = (divergence: Divergence) => divergence.id.replace(/ \d+$/, '');
export const keptBy = (decisions: readonly Decision[], pair: Pair, divergence: Divergence): Decision | undefined =>
  decisions.find((decision) =>
    decision.matches.some(
      (one) => (one.kind === undefined || one.kind === divergence.kind) && one.id === mark(divergence) && (one.property === undefined || one.property === divergence.property) && (one.state === undefined || one.state === pair.state),
    ),
  );

export function pairingDocument(pairs: readonly Pair[], decisions: readonly Decision[], faces: readonly Face[] = [], aliases: readonly Alias[] = []): string {
  const open = new Map<string, { readonly example: Divergence; readonly where: string[] }>();
  const kept = new Map<string, Set<string>>();
  const rows = pairs.map((pair) => {
    let openHere = 0;
    let keptHere = 0;
    for (const divergence of pair.divergences) {
      const decision = keptBy(decisions, pair, divergence);
      const key = `${divergence.kind} \`${mark(divergence)}\` ${divergence.property}`;
      if (decision !== undefined) {
        keptHere += 1;
        kept.set(decision.decision, (kept.get(decision.decision) ?? new Set()).add(key));
        continue;
      }
      openHere += 1;
      const entry = open.get(key) ?? { example: divergence, where: [] };
      entry.where.push(`${pair.state}/${pair.theme}/${pair.language}`);
      open.set(key, entry);
    }
    return `| ${pair.state} | ${pair.theme} | ${pair.language} | ${pair.regions} | ${pair.controls} | ${openHere} | ${keptHere} |`;
  });
  const total = [...open.values()].reduce((sum, entry) => sum + entry.where.length, 0);
  return [
    '# Pairing with the canonical design',
    '',
    'Generated by `npm run parity` (tools/parity: the app\'s e2e build and `design/final/index.html` side by side in Chrome,',
    'each of the design\'s 12 states in the dark and light themes, in English and Portuguese) and `node tools/parity/report.ts`.',
    'Never edited by hand: `tools/parity/pairing.test.ts` fails while it is out of step with `docs/pairing.json`.',
    '',
    'Every region both sides mark (`data-region`) and every control both mark (`data-door`, the n-th of each door) is',
    'measured on both sides; a divergence is a size beyond 2 px (a region\'s beyond 4), a font, a colour beyond 16 of the',
    'channels\' summed difference, or corners, where they show — or something the design draws and the app does not.',
    `Open: ${total} divergences of ${open.size} kinds. Decisions (docs/PRODUCT.md, section 4) keep the others.`,
    '',
    '| State | Theme | Language | Regions | Controls | Open | Kept by a decision |',
    '|---|---|---|---|---|---|---|',
    ...rows,
    '',
    '## Open divergences',
    '',
    '| What | Pairs | Design | App | First pairs |',
    '|---|---|---|---|---|',
    ...[...open.entries()]
      .sort((a, b) => b[1].where.length - a[1].where.length || a[0].localeCompare(b[0]))
      .map(([key, entry]) => `| ${key} | ${entry.where.length} | ${entry.example.canon} | ${entry.example.app} | ${entry.where.slice(0, 3).join(', ')} |`),
    '',
    '## Kept by a decision',
    '',
    ...decisions.map((decision) => `- **${decision.decision}** (${decision.why}): ${[...(kept.get(decision.decision) ?? [])].sort().join('; ') || 'nothing diverges by it in this run'}`),
    '',
    '## Faces measured in the app',
    '',
    'Where the app marks a door on a part of what a person sees, the thing itself is measured (tools/parity/faces.json):',
    '',
    ...faces.map((one) => `- \`${one.mark}\` (${one.side === 'app' ? 'the app' : 'the design'}): ${one.closest !== undefined ? `its closest \`${one.closest}\`` : `the \`${one.inside ?? ''}\` inside it`} — ${one.why}`),
    ...aliases.map((one) => `- \`${one.door}\`: drawn by the app as ${one.as.map((door) => `\`${door}\``).join(', ')} — ${one.why}`),
    '',
  ].join('\n');
}

export const PAIRING = path.join('docs', 'pairing.json');
export const DECISIONS = path.join('tools', 'parity', 'decisions.json');
export const DOCUMENT = path.join('docs', 'PAIRING.md');
export const readPairs = (): readonly Pair[] => (JSON.parse(fs.readFileSync(PAIRING, 'utf8')) as { pairs: Pair[] }).pairs;
export const readDecisions = (): readonly Decision[] => (JSON.parse(fs.readFileSync(DECISIONS, 'utf8')) as { decisions: Decision[] }).decisions;
export const FACES = path.join('tools', 'parity', 'faces.json');
export const readFaces = (): readonly Face[] => (JSON.parse(fs.readFileSync(FACES, 'utf8')) as { faces: Face[] }).faces;
export const readAliases = (): readonly Alias[] => (JSON.parse(fs.readFileSync(FACES, 'utf8')) as { aliases?: Alias[] }).aliases ?? [];

if (process.argv[1] !== undefined && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  fs.writeFileSync(DOCUMENT, pairingDocument(readPairs(), readDecisions(), readFaces(), readAliases()));
  console.log(`${DOCUMENT} written`);
}
